### ISSUE TITLE
Save/Load the Profile Image

### ISSUE THREAD

**Issue by ArcaneWizard** [betaoverflow/project-speakerhub#10]
Currently, the MongoDB database saves the name of a user's profile image, which isn't really useful. Figure out how the server/database can store the actual profile image and load them into user profiles.

Possible suggestion: Upload image to a server folder and store the path name to the image for each user in MongoDB

**Comment by ArcaneWizard** [comment]
Just requesting to be assigned this. About time I seriously tried my hand at the issue.

**Comment by Aniket762** [comment]
Dude sorry I have merged the PR without closing the issue. Closing this now sorry for the inconvenience
