### ISSUE TITLE
Update user profile 

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/project-speakerhub#12]
When a user is logged in give him a button that says settings or update profile. When clicked it gives them the ability to change their profile details. And also give them an option to delete their profile. Remember to use private routes. For any doubts feel free to reply in the thread!

**Comment by choudharymuskan** [comment]
Can you please elaborate the task and in which project it is required??
when a user updates his profile thereafter to display changes in the frontend. We need to update it in database . Which database you are using and which routes.

**Comment by sumana2001** [comment]
Hi @choudharymuskan 
Basically in this project, there is a separate profile page for each speaker. In that profile page we want to add a button saying update profile. On clicking the button, the user should get an option of changing his name, experience, photo etc. 
By private routes we mean, this button should be only available if you're logged in and are on only your profile page
We are using MongoDB for database. You can refer the readme for connecting to the database

Hope this helps.

**Comment by bhargavkumar7031** [comment]
Hi @Aniket762 , Can I work on this?

**Comment by sumana2001** [comment]
Sure @bhargavkumar7031 ! Go for it😄

**Comment by wise-introvert** [comment]
@bhargavkumar7031 If you're not working on this anymore, I would love to take a shot at it.

**Comment by devanshgl66** [comment]
Hi @Aniket762 , Can I work on this?

**Comment by Aniket762** [comment]
Sure @devanshgl66 go for it

**Comment by devanshgl66** [comment]
@Aniket762 can you check the pull request .

**Comment by Aniket762** [comment]
Hey @devanshgl66 thanks a lot for the pull request. It works as we expected.

**Comment by Aniket762** [comment]
@devanshgl66 sorry for the late reply was pretty piled up with other projects. Hope you don't mind. Keep contributing 🎉
