### ISSUE TITLE
Error in Registration

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/project-speakerhub#2]
When more fields were added to the registration form it stopped working. The Signup button is not redirecting anywhere and gives a deadlock. The expected behavior is when the registered corresponding card appears on the home page and single User page. With the particular credentials, the user can log in and see his/her name in the dashboard.  

Attach a screenshot after to show that the registration page is working😃

**Comment by ArcaneWizard** [comment]
Aight, I'd be down to do this issue if I can get assigned to it. I'm not 100% certain if I'll figure out how to save and load an image using a MongoDB database (for the profile image), but I could:

1.  get registration working for the other new entries + add an option to attach a profile img
2.  quickly add the new props to update the corresponding card and single User page 
3.  open a smaller issue for figuring out how to save/update just the profile image of users if I don't get that working

PS: Let me know if I should be splitting steps 1-2 as two separate pull requests if this particular issue is only about addressing step 1 first.

**Comment by Aniket762** [comment]
Hey, @ArcaneWizard you can create smaller issues and I will assign it to you. You can create as many smaller issues as you want and incase you get stuck somewhere open issues for others as well. Looking forward to the crazy changes which you bring in 😃

**Comment by Aniket762** [comment]
@all-contributors please add @ArcaneWizard  for code, doc
